version: '3.7'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    networks:
      - traefik
      - inbound
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Copies the Let's Encrypt certificate locally for ease of backing up
      - ./letsencrypt:/letsencrypt
      # Mounts the Traefik static configuration inside the Traefik container
      - ./traefik.metrics.yml:/etc/traefik/traefik.yml
      
# Add the blazorapp test service http
  owencloudinteractionblazorui:
     image: litvinovvn/owencloudinteractionblazorui
     networks:
      - inbound
     environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
     deploy:
      labels:
       - "traefik.http.routers.owencloudinteractionblazorui.rule=Host(`owencloud.achii.fvds.ru`)"
       - "traefik.http.routers.owencloudinteractionblazorui.service=owencloudinteractionblazorui"
       - "traefik.http.routers.owencloudinteractionblazorui.entrypoints=websecure"
       - "traefik.http.routers.owencloudinteractionblazorui.tls.certresolver=myresolver"
       - "traefik.http.routers.owencloudinteractionblazorui.middlewares=test-compress,test-errorpages"
       - "traefik.http.services.owencloudinteractionblazorui.loadbalancer.server.scheme=http"
       - "traefik.http.services.owencloudinteractionblazorui.loadbalancer.server.port=80"
       - "traefik.http.middlewares.test-compress.compress=true"
       - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
       - "traefik.http.middlewares.test-errorpages.errors.service=error"
       - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"
       - "traefik.docker.network=inbound"

  
# Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    networks:
      - inbound
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.error.rule=Host(`error.storage.achii.fvds.ru`)"
        - "traefik.http.routers.error.service=error"
        - "traefik.http.services.error.loadbalancer.server.port=80"
        - "traefik.http.routers.error.entrypoints=web"
        - "traefik.docker.network=inbound"



##########################################################        
############## Docker NETWORKS configuration #############
##########################################################
networks:
  traefik:
    driver: overlay
    name: traefik
  inbound:
    driver: overlay
    name: inbound