name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2        
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./OwenCloudInteraction.sln
      - name: Build
        run: dotnet build ./OwenCloudInteraction.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ./OwenCloudInteraction.sln --no-restore --verbosity normal      
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5        
        with:
          image: litvinovvn/owencloudinteractionblazorui
          tags: v1, latest
          registry: docker.io
          dockerfile: ./Source/Presentation/OwenCloudInteraction.UI.BlazorWASM/Server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            git pull
            cd OwenCloudInteraction/Production            
            bash swarmStart.sh